# docker-compose.yml
version: "3.8"

services:
  api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: leoregistry47.azurecr.io/fastapi-app:v4
    container_name: fastapi-app
    ports:
      - "8000:80"
    environment:
      - DATABASE_URL=postgresql://postgres:z5DIOIL2hs2s8kTZWn855O@db:5432/users_db
      - SECRET_KEY=supersecretkey
      - AZURE_DEVOPS_ORG=your-org
      - AZURE_DEVOPS_PROJECT=your-project
      - AZURE_DEVOPS_PAT=your-pat
      - API_VERSION=7.2-preview
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: z5DIOIL2hs2s8kTZWn855O
      POSTGRES_DB: users_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: